# Generated by Django 4.1.2 on 2022-11-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admreg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admname', models.CharField(max_length=255)),
                ('admemail', models.CharField(max_length=255)),
                ('admpassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('prodescription', models.CharField(max_length=255)),
                ('proimage', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='toyreg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='pay_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalp', models.CharField(max_length=255)),
                ('pstatus', models.CharField(default='pending', max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.toyreg_tb')),
            ],
        ),
        migrations.CreateModel(
            name='check_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('pnumber', models.CharField(max_length=255)),
                ('landm', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.toyreg_tb')),
            ],
        ),
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqty', models.CharField(max_length=255)),
                ('totalprice', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.product_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toyapp.toyreg_tb')),
            ],
        ),
    ]
